#!/usr/bin/env python3
"""Generate the project-specific `schema` module of the trusted library from a
frozen classification (TOML). Deterministic: same input, same output.

Usage: gen_schema.py <classification.toml> <output schema.rs>
"""

import re
import sys
import tomllib

FORMAT = "no-secrets-in-logs/classification/v1"

# view name -> permission trait
VIEW_TRAITS = {
    "eq": "crate::declassify::AllowEq",
    "eq_public": "crate::declassify::AllowEqPublic",
    "known_identifier": "crate::declassify::AllowKnownIdentifier",
    "check": "crate::declassify::AllowCheck",
    "len": "crate::declassify::AllowLen",
    "keyed_hash": "crate::crypto::AllowKeyedHash",
    "password_hash": "crate::crypto::AllowPasswordHash",
    "digest": "crate::crypto::AllowDigest",
}
LABELS = {"public", "secret", "u64"}
IDENT = re.compile(r"^[a-z][a-z0-9_]*$")
COMMAND = re.compile(r"^[a-z][a-z0-9-]*$")
RUST_KEYWORDS = {"type", "match", "fn", "struct", "enum", "mod", "use", "impl", "self", "ref", "loop", "move"}


class ClassificationError(Exception):
    pass


def pascal(name):
    return "".join(p.capitalize() for p in re.split(r"[_-]", name))


def check_ident(name, what):
    if not IDENT.match(name) or name in RUST_KEYWORDS:
        raise ClassificationError(f"invalid {what} name: {name!r}")


def parse(doc):
    if doc.get("format") != FORMAT:
        raise ClassificationError(f"format must be {FORMAT!r}")
    kinds = {}
    for name, spec in sorted(doc.get("kinds", {}).items()):
        check_ident(name, "kind")
        unknown = set(spec) - {"description", "views", "deliver", "generate"}
        if unknown:
            raise ClassificationError(f"kind {name}: unknown keys {sorted(unknown)}")
        views, last_n, eq_with = [], None, []
        for v in spec.get("views", []):
            if v.startswith("eq_with:"):
                eq_with.append(v.split(":", 1)[1])
            elif v.startswith("last_n:"):
                n = int(v.split(":", 1)[1])
                if n <= 0:
                    raise ClassificationError(f"kind {name}: last_n must be positive")
                last_n = n
            elif v in VIEW_TRAITS:
                views.append(v)
            else:
                raise ClassificationError(f"kind {name}: unknown view {v!r}")
        generate = spec.get("generate")
        if generate is not None:
            m = re.match(r"^(hex|digits):([1-9][0-9]*)$", generate)
            if not m:
                raise ClassificationError(f"kind {name}: generate must be hex:N or digits:N")
            generate = (m.group(1), int(m.group(2)))
        kinds[name] = {
            "description": spec.get("description", ""),
            "views": sorted(set(views)),
            "last_n": last_n,
            "eq_with": sorted(set(eq_with)),
            "deliver": bool(spec.get("deliver", False)),
            "generate": generate,
        }
    for name, k in kinds.items():
        for other in k["eq_with"]:
            if other not in kinds:
                raise ClassificationError(f"kind {name}: eq_with refers to unknown kind {other!r}")
    commands = []
    seen = set()
    for cmd in doc.get("commands", []):
        name = cmd["name"]
        if not COMMAND.match(name) or name in seen:
            raise ClassificationError(f"invalid or duplicate command name: {name!r}")
        seen.add(name)
        args = []
        for arg in cmd.get("args", []):
            check_ident(arg["name"], "argument")
            if arg["label"] not in LABELS:
                raise ClassificationError(f"{name}.{arg['name']}: label must be one of {sorted(LABELS)}")
            if arg["label"] == "secret":
                if arg.get("kind") not in kinds:
                    raise ClassificationError(f"{name}.{arg['name']}: unknown kind {arg.get('kind')!r}")
            elif "kind" in arg:
                raise ClassificationError(f"{name}.{arg['name']}: only secret arguments have a kind")
            args.append(arg)
        commands.append({"name": name, "args": args})
    return kinds, commands


def rust_type(arg):
    if arg["label"] == "public":
        return "Public"
    if arg["label"] == "u64":
        return "u64"
    return f"Secret<{pascal(arg['kind'])}>"


def generate(kinds, commands, source_name):
    out = []
    w = out.append
    w("// @generated by codegen/gen_schema.py from " + source_name + ". DO NOT EDIT.")
    w("// Part of the trusted base: the gate regenerates this file and compares it.")
    w("")
    w("#![allow(unused_imports)]")
    w("use vstd::prelude::*;")
    w("use crate::label::{Kind, Public, Secret};")
    w("")
    w("verus! {")
    w("")
    for name, k in kinds.items():
        t = pascal(name)
        if k["description"]:
            w(f"/// Secret kind `{name}`: {k['description']}")
        else:
            w(f"/// Secret kind `{name}`.")
        w(f"pub struct {t};")
        w(f"impl Kind for {t} {{}}")
        for v in k["views"]:
            w(f"impl {VIEW_TRAITS[v]} for {t} {{}}")
        for other in k["eq_with"]:
            w(f"impl crate::declassify::AllowEqWith<{pascal(other)}> for {t} {{}}")
        if k["last_n"] is not None:
            w(f"impl crate::declassify::AllowLastN for {t} {{}}")
        if k["deliver"]:
            w(f"impl crate::output::Deliverable for {t} {{}}")
        if k["generate"] is not None:
            w(f"impl crate::crypto::Generated for {t} {{}}")
        w("")
        if k["last_n"] is not None:
            n = k["last_n"]
            w(f"/// View `last_n:{n}` of kind `{name}`.")
            w(f"pub fn last_n_{name}(a: &Secret<{t}>) -> (r: Public)")
            w(f"    requires {n} <= a@.len(),")
            w(f"    ensures r@ == a@.subrange(a@.len() - {n}, a@.len() as int),")
            w("{")
            w(f"    crate::declassify::last_n(a, {n})")
            w("}")
            w("")
        if k["generate"] is not None:
            how, n = k["generate"]
            fn = "random_hex" if how == "hex" else "random_digits"
            w(f"/// Generate a fresh `{name}` ({how}, {n} characters) from the OS CSPRNG.")
            w(f"pub fn generate_{name}() -> (r: Secret<{t}>)")
            w(f"    ensures r@.len() == {n},")
            w("{")
            w(f"    crate::crypto::{fn}::<{t}>({n})")
            w("}")
            w("")
    w("/// A parsed input line. Secret arguments arrive already labeled.")
    w("pub enum Command {")
    for c in commands:
        fields = ", ".join(f"{a['name']}: {rust_type(a)}" for a in c["args"])
        w(f"    {pascal(c['name'])} {{ {fields} }}," if fields else f"    {pascal(c['name'])},")
    w("    /// A known command with wrong arguments (`command` is its name), or an")
    w("    /// unknown command (`command` is `<unknown>`). Arguments are dropped.")
    w("    Invalid { command: Public },")
    w("    /// An empty line.")
    w("    Empty,")
    w("}")
    w("")
    w("/// Read and parse the next input line. `None` at end of input.")
    w("#[verifier::external_body]")
    w("pub fn next_command() -> Option<Command> {")
    w("    let tokens = crate::input::read_tokens()?;")
    w("    if tokens.is_empty() {")
    w("        return Some(Command::Empty);")
    w("    }")
    w("    let name: String = tokens[0].iter().collect();")
    w("    let args = &tokens[1..];")
    w("    let cmd = match name.as_str() {")
    for c in commands:
        n = len(c["args"])
        w(f"        \"{c['name']}\" => {{")
        w(f"            if args.len() != {n} {{")
        w(f"                return Some(Command::Invalid {{ command: Public::lit(\"{c['name']}\") }});")
        w("            }")
        parts = []
        for i, a in enumerate(c["args"]):
            if a["label"] == "public":
                parts.append(f"{a['name']}: Public::from_chars(args[{i}].clone())")
            elif a["label"] == "secret":
                parts.append(f"{a['name']}: Secret::from_chars(args[{i}].clone())")
            else:
                w(f"            let Some({a['name']}) = crate::input::parse_u64(&args[{i}]) else {{")
                w(f"                return Some(Command::Invalid {{ command: Public::lit(\"{c['name']}\") }});")
                w("            };")
                parts.append(a["name"])
        if parts:
            w(f"            Command::{pascal(c['name'])} {{ {', '.join(parts)} }}")
        else:
            w(f"            Command::{pascal(c['name'])}")
        w("        }")
    w("        _ => Command::Invalid { command: Public::lit(\"<unknown>\") },")
    w("    };")
    w("    Some(cmd)")
    w("}")
    w("")
    w("} // verus!")
    w("")
    return "\n".join(out)


def main(argv):
    if len(argv) != 3:
        print(__doc__, file=sys.stderr)
        return 2
    with open(argv[1], "rb") as f:
        doc = tomllib.load(f)
    try:
        kinds, commands = parse(doc)
    except (ClassificationError, KeyError, ValueError) as e:
        print(f"classification error: {e}", file=sys.stderr)
        return 1
    src = generate(kinds, commands, argv[1].rsplit("/", 1)[-1])
    with open(argv[2], "w") as f:
        f.write(src)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
