#!/usr/bin/env python3
"""Generate project-specific CodeQL barrier models (schema::last_n_*) from a
frozen classification. Deterministic.

Usage: gen_codeql_models.py <classification.toml> <output .model.yml>
"""

import sys
import tomllib

sys.path.insert(0, __file__.rsplit("/", 1)[0])
from gen_schema import parse  # noqa: E402


def main(argv):
    if len(argv) != 3:
        print(__doc__, file=sys.stderr)
        return 2
    with open(argv[1], "rb") as f:
        kinds, _ = parse(tomllib.load(f))
    rows = [
        f'      - ["nosecrets::schema::last_n_{name}", "ReturnValue", "log-injection", "manual"]'
        for name, k in kinds.items() if k["last_n"] is not None
    ]
    with open(argv[2], "w") as f:
        f.write("# @generated by codegen/gen_codeql_models.py. DO NOT EDIT.\n")
        f.write("extensions:\n")
        f.write("  - addsTo:\n      pack: codeql/rust-all\n      extensible: barrierModel\n")
        f.write("    data:\n")
        f.write("\n".join(rows) if rows else "      []")
        f.write("\n")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
