// @generated by codegen/gen_schema.py from demo.classification.toml. DO NOT EDIT.
// Part of the trusted base: the gate regenerates this file and compares it.

#![allow(unused_imports)]
use vstd::prelude::*;
use crate::label::{Kind, Public, Secret};

verus! {

/// Secret kind `api_key`: an API key, shown once on creation
pub struct ApiKey;
impl Kind for ApiKey {}
impl crate::declassify::AllowCheck for ApiKey {}
impl crate::crypto::AllowDigest for ApiKey {}
impl crate::declassify::AllowEq for ApiKey {}
impl crate::declassify::AllowLastN for ApiKey {}
impl crate::output::Deliverable for ApiKey {}
impl crate::crypto::Generated for ApiKey {}

/// View `last_n:4` of kind `api_key`.
pub fn last_n_api_key(a: &Secret<ApiKey>) -> (r: Public)
    requires 4 <= a@.len(),
    ensures r@ == a@.subrange(a@.len() - 4, a@.len() as int),
{
    crate::declassify::last_n(a, 4)
}

/// Generate a fresh `api_key` (hex, 32 characters) from the OS CSPRNG.
pub fn generate_api_key() -> (r: Secret<ApiKey>)
    ensures r@.len() == 32,
{
    crate::crypto::random_hex::<ApiKey>(32)
}

/// Secret kind `email`: an email address
pub struct Email;
impl Kind for Email {}
impl crate::declassify::AllowCheck for Email {}
impl crate::declassify::AllowEq for Email {}
impl crate::crypto::AllowKeyedHash for Email {}
impl crate::output::Deliverable for Email {}

/// Secret kind `identifier`: a submitted login identifier (may be a mistyped password)
pub struct Identifier;
impl Kind for Identifier {}
impl crate::declassify::AllowEqPublic for Identifier {}
impl crate::declassify::AllowKnownIdentifier for Identifier {}

/// Secret kind `password`: a user's password
pub struct Password;
impl Kind for Password {}
impl crate::declassify::AllowCheck for Password {}
impl crate::crypto::AllowPasswordHash for Password {}

/// Secret kind `pin`: a one-time numeric code
pub struct Pin;
impl Kind for Pin {}
impl crate::declassify::AllowCheck for Pin {}
impl crate::declassify::AllowEq for Pin {}
impl crate::declassify::AllowLen for Pin {}
impl crate::output::Deliverable for Pin {}
impl crate::crypto::Generated for Pin {}

/// Generate a fresh `pin` (digits, 6 characters) from the OS CSPRNG.
pub fn generate_pin() -> (r: Secret<Pin>)
    ensures r@.len() == 6,
{
    crate::crypto::random_digits::<Pin>(6)
}

/// A parsed input line. Secret arguments arrive already labeled.
pub enum Command {
    Signup { user: Public, email: Secret<Email>, password: Secret<Password> },
    Signin { identifier: Secret<Identifier>, password: Secret<Password> },
    UseKey { key: Secret<ApiKey> },
    Wait { minutes: u64 },
    Quit,
    Probe { user: Public, email: Secret<Email>, password: Secret<Password>, identifier: Secret<Identifier>, key: Secret<ApiKey>, pin: Secret<Pin> },
    /// A known command with wrong arguments (`command` is its name), or an
    /// unknown command (`command` is `<unknown>`). Arguments are dropped.
    Invalid { command: Public },
    /// An empty line.
    Empty,
}

/// Read and parse the next input line. `None` at end of input.
#[verifier::external_body]
pub fn next_command() -> Option<Command> {
    let tokens = crate::input::read_tokens()?;
    if tokens.is_empty() {
        return Some(Command::Empty);
    }
    let name: String = tokens[0].iter().collect();
    let args = &tokens[1..];
    let cmd = match name.as_str() {
        "signup" => {
            if args.len() != 3 {
                return Some(Command::Invalid { command: Public::lit("signup") });
            }
            Command::Signup { user: Public::from_chars(args[0].clone()), email: Secret::from_chars(args[1].clone()), password: Secret::from_chars(args[2].clone()) }
        }
        "signin" => {
            if args.len() != 2 {
                return Some(Command::Invalid { command: Public::lit("signin") });
            }
            Command::Signin { identifier: Secret::from_chars(args[0].clone()), password: Secret::from_chars(args[1].clone()) }
        }
        "use-key" => {
            if args.len() != 1 {
                return Some(Command::Invalid { command: Public::lit("use-key") });
            }
            Command::UseKey { key: Secret::from_chars(args[0].clone()) }
        }
        "wait" => {
            if args.len() != 1 {
                return Some(Command::Invalid { command: Public::lit("wait") });
            }
            let Some(minutes) = crate::input::parse_u64(&args[0]) else {
                return Some(Command::Invalid { command: Public::lit("wait") });
            };
            Command::Wait { minutes }
        }
        "quit" => {
            if args.len() != 0 {
                return Some(Command::Invalid { command: Public::lit("quit") });
            }
            Command::Quit
        }
        "probe" => {
            if args.len() != 6 {
                return Some(Command::Invalid { command: Public::lit("probe") });
            }
            Command::Probe { user: Public::from_chars(args[0].clone()), email: Secret::from_chars(args[1].clone()), password: Secret::from_chars(args[2].clone()), identifier: Secret::from_chars(args[3].clone()), key: Secret::from_chars(args[4].clone()), pin: Secret::from_chars(args[5].clone()) }
        }
        _ => Command::Invalid { command: Public::lit("<unknown>") },
    };
    Some(cmd)
}

} // verus!
